package br.com.cafebinario.iso8583.dao;

public class SQL_LOADER_CTL {
	
	public static String bindParameter(String inFile, String badFile, String discardFile){
		return SQL_LOADER_CTL.CTL.replace("${IN_FILE}", inFile).replace("${BAD_FILE}", badFile).replace("${DISCARD_FILE}", discardFile);
	}
	
	public static String CTL =    "LOAD DATA\n" 
								+ "  INFILE '${IN_FILE}'\n"
								+ "  BADFILE '${BAD_FILE}'\n" 
								+ "  DISCARDFILE '${DISCARD_FILE}'\n"
								+ "  APPEND\n" + "  INTO TABLE PROCESSED_FILES\n"
								+ "  WHEN (01) = 'P' and (02) = 'F'\n" + "  (\n"
								+ "      ROW_TYPE POSITION(1:2),\n"
								+ "      PROCESS_FILE_ID POSITION(3:27),\n"
								+ "      FILE_NAME POSITION(28:58),\n"
								+ "      PROC_DATE POSITION(59:66),\n"
								+ "      PROC_TIME POSITION(67:72),\n"
								+ "      SUM_AMOUNT POSITION(73:90),\n"
								+ "      NRO_RECORDS POSITION(91:108)\n" + "  )\n" + "\n"
								+ "  INTO TABLE CONTROL_FILES\n"
								+ "  WHEN (01) = 'C' and (02) = 'F'\n" + "  (\n"
								+ "      CONTROL_FILE_ID \"SQ_CONTROL_FILE.NEXTVAL\",\n"
								+ "      ROW_TYPE POSITION(1:2),\n"
								+ "      PROCESS_FILE_ID POSITION(3:27),\n"
								+ "      TRAN_CODE POSITION(28:31),\n"
								+ "      USAGE_CODE POSITION(32:34),\n"
								+ "      FILE_TYPE POSITION(35:37),\n"
								+ "      FILE_REFERENCE_DATE POSITION(38:43),\n"
								+ "      PROCESSOR_ID POSITION(44:54),\n"
								+ "      FILE_SEQUENCE_NUMBER POSITION(55:59),\n"
								+ "      FILE_AMOUNT POSITION(60:77),\n"
								+ "      FILE_COUNTS POSITION(78:89),\n"
								+ "      MESSAGE_NUMBER POSITION(90:107)\n" + "  )\n" + "\n"
								+ "  INTO TABLE EXCHANGE_MC_FINAN_ADDENDUM\n"
								+ "  WHEN (01) = 'F' and (02) = 'A'\n" + "  (\n"
								+ "      EXCHANGE_ID \"SQ_EXCHANGE_ID.CURRVAL\",\n"
								+ "      CONTROL_FILE_ID \"SQ_CONTROL_FILE.CURRVAL\",\n"
								+ "      ROW_TYPE POSITION(1:2),\n"
								+ "      TRAN_CODE POSITION(3:6),\n"
								+ "      USAGE_CODE POSITION(7:10),\n"
								+ "      FORWARDING_INST_ID POSITION(11:21),\n"
								+ "      ORI_MESSAGE_FORMAT POSITION(22:22),\n"
								+ "      TRANS_DESCRIPTION POSITION(23:38),\n"
								+ "      FORM_DESCRIPTION POSITION(39:93),\n"
								+ "      TRANS_LIFE_CICLYE_ID POSITION(94:109),\n"
								+ "      MESSAGE_NUMBER POSITION(110:118),\n"
								+ "      TRANS_DEST_INST_ID POSITION(119:129),\n"
								+ "      TRANS_ORI_INST_ID POSITION(130:140)\n" + "  )\n" + "\n"
								+ "  INTO TABLE EXCHANGE_MASTER_TABLE\n"
								+ "  WHEN (01) = 'M' and (02) = 'T'\n" + "  (\n"
								+ "      EXCHANGE_ID \"SQ_EXCHANGE_ID.NEXTVAL\",\n"
								+ "      CONTROL_FILE_ID \"SQ_CONTROL_FILE.CURRVAL\",\n"
								+ "      ROW_TYPE POSITION(1:2),\n"
								+ "      BRAND_ID POSITION(3:4),\n"
								+ "      PRODUCT_ID POSITION(5:7),\n"
								+ "      SOURCE POSITION(8:8),\n"
								+ "      INSTALLMENT POSITION(9:17),\n"
								+ "      CARD_NUMBER POSITION(18:36),\n"
								+ "      TRAN_CODE POSITION(37:40),\n"
								+ "      PROC_CODE POSITION(41:46),\n"
								+ "      REASON_CODE POSITION(47:50),\n"
								+ "      USAGE_CODE POSITION(51:54),\n"
								+ "      ACQR_REF_NUMBER POSITION(55:77),\n"
								+ "      TRANS_CURRENCY POSITION(78:80),\n"
								+ "      TRANS_AMOUNT POSITION(81:98),\n"
								+ "      FEE_CURRENCY POSITION(99:101),\n"
								+ "      FEE_OPERATION POSITION(102:102),\n"
								+ "      FEE_AMOUNT POSITION(103:114),\n"
								+ "      PROCESS_FILE_ID POSITION(115:139),\n"
								+ "      MESSAGE_NUMBER POSITION(140:157)\n" + "  )\n" + "\n"
								+ "  INTO TABLE EXCHANGE_MC_PRESENTMENT_EXT\n"
								+ "  WHEN (01) = 'F' and (02) = 'P'\n" + "  (\n"
								+ "      EXCHANGE_ID \"SQ_EXCHANGE_ID.CURRVAL\",\n"
								+ "      ROW_TYPE POSITION(1:2),\n"
								+ "      INSTALLMENT_TOTAL POSITION(3:5),\n"
								+ "      INSTALLMENT_NUMBER POSITION(6:8),\n"
								+ "      TRANS_DEST_INST_ID POSITION(9:19),\n"
								+ "      TRANS_ORI_INST_ID POSITION(20:30),\n"
								+ "      RECONCILIATION_AMOUNT POSITION(31:48),\n"
								+ "      RECONCILIATION_RATE_CONV POSITION(49:60),\n"
								+ "      ORIGINAL_AMOUNT_CURRENCY POSITION(61:63),\n"
								+ "      ORIGINAL_AMOUNT_TRANS POSITION(64:81),\n"
								+ "      ORIGINAL_RECON_CURRENCY POSITION(82:84),\n"
								+ "      ORIGINAL_AMOUNT_RECON POSITION(85:96),\n"
								+ "      LOCAL_DATE POSITION(97:104),\n"
								+ "      LOCAL_TIME POSITION(105:110),\n"
								+ "      BUSINESS_ACTIVITY POSITION(111:139),\n"
								+ "      COUNTRY_CODE POSITION(140:140),\n"
								+ "      RISK_APROVAL_CODE POSITION(141:151),\n"
								+ "      TRANS_LIFE_CICLYE_ID POSITION(152:167),\n"
								+ "      POS_DATA_CODE POSITION(168:217),\n" 
								+ "      MESSAGE_REVERSAL_IND POSITION(218:218)"
								+ "  )\n" + "\n"
								+ "  INTO TABLE EXCHANGE_MC_FEE_COLLECTION_EXT\n"
								+ "  WHEN (01) = 'F' and (02) = 'C'\n" + "  (\n"
								+ "      EXCHANGE_ID \"SQ_EXCHANGE_ID.CURRVAL\",\n"
								+ "      ROW_TYPE POSITION(1:2),\n"
								+ "      TRANS_DEST_INST_ID POSITION(3:13),\n"
								+ "      TRANS_ORI_INST_ID POSITION(14:24),\n"
								+ "      ACQR_INST_ID POSITION(25:35),\n"
								+ "      FORWARDING_INST_ID POSITION(36:46),\n"
								+ "      CARD_SEQUENCE_NUMBER POSITION(47:49),\n"
								+ "      CARD_ISSUER_REFERENCE_DATA POSITION(50:59),\n"
								+ "      CURRENCY_CODE_TRANS POSITION(60:62),\n"
								+ "      CURRENCY_CODE_RECONCILIATION POSITION(63:65),\n"
								+ "      TRANS_LIFE_CICLYE_ID POSITION(66:81),\n"
								+ "      OPERATION POSITION(82:82),\n"
								+ "      RECONCILIATION_AMOUNT POSITION(83:100),\n"
								+ "      RECONCILIATION_RATE_CONV POSITION(101:112),\n"
								+ "      ORIGINAL_AMOUNT_CURRENCY POSITION(113:115),\n"
								+ "      ORIGINAL_AMOUNT_TRANS POSITION(116:127),\n"
								+ "      ORIGINAL_RECON_CURRENCY POSITION(128:130),\n"
								+ "      ORIGINAL_AMOUNT_RECON POSITION(131:142),\n"
								+ "      RECEIVING_INST_ID POSITION(143:151),\n"
								+ "      DATE_ACTION POSITION(152:157),\n"
								+ "      DATA_RECORD POSITION(158:257) \"TRIM(:DATA_RECORD)\",\n"
								+ "      GCMS_PRODUCT_IDENT POSITION(258:260),\n"
								+ "      MESSAGE_REVERSAL_IND POSITION(261:261),\n"
								+ "      ORIG_PROC_DATE POSITION(262:267),\n"
								+ "      FEE_COLLECTION_CONTRO_NUM POSITION(268:277),\n"
								+ "      CURRENCY_EXPONENTS POSITION(278:337),\n"
								+ "      CURRENCY_CODE_ORI_AMOUNT POSITION(338:343),\n"
								+ "      BUSINESS_ACTIVITY POSITION(344:372),\n"
								+ "      SETTLEMENT_DATA POSITION(373:439),\n"
								+ "      SETTLEMENT_INDICATOR POSITION(440:469),\n"
								+ "      ORI_MESSAGE_FORMAT POSITION(470:470),\n"
								+ "      FULFILLMENT_DOC_CODE POSITION(471:471),\n"
								+ "      MASTERCOM_NUMBER POSITION(472:478),\n"
								+ "      ORI_REASON_RET_REQUEST POSITION(479:483)\n" + "  )\n"
								+ "\n" + "  INTO TABLE EXCHANGE_MC_ADM\n"
								+ "  WHEN (01) = 'M' and (02) = 'A'\n" + "  (\n"
								+ "      EXCHANGE_ID \"SQ_EXCHANGE_ID.CURRVAL\",\n"
								+ "      MCC POSITION(1:4),\n"
								+ "      TRANS_DEST_INST_ID POSITION(5:15),\n"
								+ "      TRANS_REC_INT_ID POSITION(16:26),\n"
								+ "      CURRENCY_CODE POSITION(27:29),\n"
								+ "      CURRENCY_EXPONENT POSITION(30:30),\n"
								+ "      SETTLEMENT_INDICATOR POSITION(31:61),\n"
								+ "      TRANS_CURRENCY POSITION(62:64),\n"
								+ "      CURRENCY_CODE_RECONCILIATION POSITION(65:67),\n"
								+ "      RECONCILED_FILE POSITION(68:92),\n"
								+ "      FILE_COUNTS POSITION(93:104),\n"
								+ "      REC_BUS_ACT POSITION(105:129),\n"
								+ "      REC_SET_ACT POSITION(130:196),\n"
								+ "      REC_CARD_PROG POSITION(197:199),\n"
								+ "      REC_TRANS_FUNC_GROUP POSITION(200:201),\n"
								+ "      REC_ACQ_BIN POSITION(202:207),\n"
								+ "      REC_ACCOUNT_RANGE POSITION(208:245),\n"
								+ "      REC_TRANS_FUNC POSITION(246:252),\n"
								+ "      REC_PROC_CODE POSITION(253:254),\n"
								+ "      REC_MEMBER_IND POSITION(255:304),\n"
								+ "      ORI_REV_TOTAL_INDICATOR POSITION(305:305),\n"
								+ "      TRANS_AMOUNT_DEBIT POSITION(307:323),\n"
								+ "      TRANS_AMOUNT_CREDIT POSITION(325:343)\n" + "  )";
}
